name: Hello flow programado
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Diga olá a cada 5 minutos
        run: echo "Hello world!"
